// The ssh config the extension hands to Remote-SSH.
//
// Remote-SSH shells out to the real `ssh`, so the only way to tell it
// where to connect is a config file. This generates one into the
// extension's own storage and is pointed at by the `remote.SSH.configFile`
// setting. It never touches `~/.ssh/config`: that file is the user's,
// and an extension editing it is the kind of help nobody asked for.

import { chmod, mkdir, writeFile } from "node:fs/promises";
import { homedir } from "node:os";
import { join, resolve } from "node:path";
import { accessPointSlug } from "./accessPoints";

/** Where to reach a job. */
export interface HostSpec {
	/** The name that appears in the `vscode-remote://ssh-remote+<alias>` URI. */
	alias: string;
	/** The access point's SSH gateway, as users reach it. */
	gatewayHost: string;
	/** Its port. 22 in front of a load balancer, 2222 direct. */
	gatewayPort: number;
	/**
	 * What the gateway should connect us to: `12345.0` for a job,
	 * `+work` for a named session, empty for the default one.
	 */
	target: string;
}

/** The key and certificate `ssh` should present. */
export interface Identity {
	privateKey: string;
	certificate: string;
}

export interface ConfigPaths {
	configFile: string;
	knownHosts: string;
}

export function configPaths(storageDir: string): ConfigPaths {
	return {
		configFile: join(storageDir, "ssh_config"),
		knownHosts: join(storageDir, "known_hosts"),
	};
}

/**
 * Write the config and return where it went.
 *
 * `knownHostsLine` is the `@cert-authority` line from
 * `GET /api/v1/ssh/ca`.
 */
export async function writeSSHConfig(
	storageDir: string,
	hosts: HostSpec[],
	knownHostsLine: string,
	identity: Identity,
	chainedConfig?: string
): Promise<ConfigPaths> {
	const paths = configPaths(storageDir);
	await mkdir(storageDir, { recursive: true, mode: 0o700 });

	await writeFile(paths.knownHosts, `${knownHostsLine.trim()}\n`, { mode: 0o600 });
	await chmod(paths.knownHosts, 0o600);

	await writeFile(
		paths.configFile,
		renderConfig(hosts, paths.knownHosts, identity, chainTarget(chainedConfig, paths.configFile)),
		{ mode: 0o600 }
	);
	// As with the key files: writeFile applies its mode only when it
	// creates the file, so an existing one keeps whatever it had.
	await chmod(paths.configFile, 0o600);

	return paths;
}

/** Render the config text. Exported for tests. */
export function renderConfig(
	hosts: HostSpec[],
	knownHostsFile: string,
	identity: Identity,
	chainedConfig: string = join(homedir(), ".ssh", "config")
): string {
	const lines: string[] = [
		"# Generated by the HTCondor extension. Edits are overwritten.",
		"#",
		"# Our Host blocks come FIRST and the user's config is included",
		"# after them, which is the opposite of what looks natural. ssh",
		"# takes the FIRST value it obtains for each keyword, so a user",
		"# whose own config opens with `Host *` would otherwise override",
		"# the settings that make these hosts work at all.",
		"",
	];

	for (const host of hosts) {
		lines.push(...renderHost(host, knownHostsFile, identity), "");
	}

	lines.push(
		"# Everything else the user configured, still in force.",
		`Include ${quote(chainedConfig)}`,
		""
	);
	return lines.join("\n");
}

/**
 * The config file this one should include.
 *
 * `remote.SSH.configFile` replaces the user's config for EVERY
 * Remote-SSH host, not just ours, so whatever it held has to be
 * included or their other hosts stop resolving. Defaulting straight to
 * `~/.ssh/config` would silently drop a file they had already pointed
 * the setting at.
 *
 * `ourConfig` is excluded, and that is not defensive tidying -- it is
 * the bug this argument exists for. Connecting sets
 * `remote.SSH.configFile` to our file, so the NEXT connection reads our
 * own path back out of the setting and includes it from inside itself.
 * ssh follows that until it gives up with "Too many recursive
 * configuration includes", and the session never opens. Everything
 * works once and then stops, which is the worst shape of bug to meet.
 */
export function chainTarget(existingSetting: string | undefined, ourConfig: string): string {
	const existing = (existingSetting ?? "").trim();
	if (existing === "" || samePath(existing, ourConfig)) {
		return defaultUserConfig();
	}
	return existing;
}

/** Whether two paths name the same file, as far as can be told. */
function samePath(a: string, b: string): boolean {
	const normalise = (p: string): string => resolve(p.replace(/^~(?=\/|\\|$)/, homedir()));
	const left = normalise(a);
	const right = normalise(b);
	// macOS and Windows are case-insensitive in practice, and getting
	// this wrong reintroduces the recursion rather than merely being
	// untidy.
	return left === right || left.toLowerCase() === right.toLowerCase();
}

function defaultUserConfig(): string {
	return join(homedir(), ".ssh", "config");
}

function renderHost(host: HostSpec, knownHostsFile: string, identity: Identity): string[] {
	const lines = [
		`Host ${host.alias}`,
		`    HostName ${host.gatewayHost}`,
		`    Port ${host.gatewayPort}`,
	];

	// The username names the job or session to reach; it carries no
	// identity, because the relay already established that. An empty target
	// means the caller's default session, and ssh sends the local
	// username when none is given -- which would name a session after
	// whatever the laptop calls its owner. `default` says it outright.
	lines.push(`    User ${host.target.trim() === "" ? "default" : host.target.trim()}`);

	lines.push(
		`    UserKnownHostsFile ${quote(knownHostsFile)}`,
		"    StrictHostKeyChecking yes",
		// The certificate is the credential. IdentitiesOnly keeps ssh
		// from announcing every key in the user's agent first: the
		// gateway has no interest in them, and each offer spends one of
		// its authentication attempts.
		`    IdentityFile ${quote(identity.privateKey)}`,
		`    CertificateFile ${quote(identity.certificate)}`,
		"    IdentitiesOnly yes",
		"    IdentityAgent none",
		// Nothing else is worth trying. Without these a certificate
		// that has just expired falls through to a password prompt
		// against a gateway that has no passwords, which reads as a
		// hang rather than as "sign in again".
		"    PasswordAuthentication no",
		"    KbdInteractiveAuthentication no",
		// Remote-SSH opens several channels over one connection; a
		// dropped keepalive mid-edit shows up as the editor
		// disconnecting for no visible reason.
		"    ServerAliveInterval 30",
		"    ServerAliveCountMax 6"
	);
	return lines;
}

/**
 * Quote a path for ssh_config.
 *
 * Needed on Windows before anywhere else: the extension's storage
 * directory sits under a user profile, and a user called "Jo Smith"
 * produces a path with a space in it that ssh otherwise reads as two
 * arguments.
 */
function quote(path: string): string {
	return `"${path.replace(/"/g, '\\"')}"`;
}

/**
 * A stable, filesystem-safe Host alias for a target.
 *
 * The access point is in the name because the alias is what the
 * generated ssh_config keys on and what Remote-SSH remembers. Job
 * 12345.0 exists on more than one access point, and two of them under
 * one alias would be one host that means different things depending on
 * when you opened it.
 */
export function aliasFor(accessPoint: string, target: string): string {
	const cleaned = target.replace(/[^A-Za-z0-9._+-]/g, "");
	const where = accessPointSlug(accessPoint);
	return `condor-${where === "" ? "" : `${where}-`}${cleaned === "" ? "default" : cleaned}`;
}
