// The ssh config the extension hands to Remote-SSH.
//
// Remote-SSH shells out to the real `ssh`, so the only way to tell it
// where to connect is a config file. This generates one into the
// extension's own storage and is pointed at by the `remote.SSH.configFile`
// setting. It never touches `~/.ssh/config`: that file is the user's,
// and an extension editing it is the kind of help nobody asked for.

import { chmod, mkdir, writeFile } from "node:fs/promises";
import { homedir } from "node:os";
import { join } from "node:path";

/** Where to reach a job, once the relay is listening. */
export interface HostSpec {
	/** The name that appears in the `vscode-remote://ssh-remote+<alias>` URI. */
	alias: string;
	/** The loopback port the relay is listening on. */
	port: number;
	/**
	 * What the gateway should connect us to: `12345.0` for a job,
	 * `+work` for a named session, empty for the default one.
	 */
	target: string;
	/**
	 * The name the gateway's host certificate is issued for, when the
	 * access point published one. See hostKeyAlias below for why this
	 * matters more than it looks.
	 */
	gatewayName?: string;
}

export interface ConfigPaths {
	configFile: string;
	knownHosts: string;
}

export function configPaths(storageDir: string): ConfigPaths {
	return {
		configFile: join(storageDir, "ssh_config"),
		knownHosts: join(storageDir, "known_hosts"),
	};
}

/**
 * Write the config and return where it went.
 *
 * `knownHostsLine` is the `@cert-authority` line from
 * `GET /api/v1/ssh/ca`.
 */
export async function writeSSHConfig(
	storageDir: string,
	hosts: HostSpec[],
	knownHostsLine: string
): Promise<ConfigPaths> {
	const paths = configPaths(storageDir);
	await mkdir(storageDir, { recursive: true, mode: 0o700 });

	await writeFile(paths.knownHosts, `${knownHostsLine.trim()}\n`, { mode: 0o600 });
	await chmod(paths.knownHosts, 0o600);

	await writeFile(paths.configFile, renderConfig(hosts, paths.knownHosts), { mode: 0o600 });
	// As with the key files: writeFile applies its mode only when it
	// creates the file, so an existing one keeps whatever it had.
	await chmod(paths.configFile, 0o600);

	return paths;
}

/** Render the config text. Exported for tests. */
export function renderConfig(hosts: HostSpec[], knownHostsFile: string): string {
	const lines: string[] = [
		"# Generated by the HTCondor extension. Edits are overwritten.",
		"#",
		"# Our Host blocks come FIRST and the user's config is included",
		"# after them, which is the opposite of what looks natural. ssh",
		"# takes the FIRST value it obtains for each keyword, so a user",
		"# whose own config opens with `Host *` would otherwise override",
		"# the settings that make these hosts work at all.",
		"",
	];

	for (const host of hosts) {
		lines.push(...renderHost(host, knownHostsFile), "");
	}

	lines.push(
		"# Everything else the user configured, still in force.",
		`Include ${quote(join(homedir(), ".ssh", "config"))}`,
		""
	);
	return lines.join("\n");
}

function renderHost(host: HostSpec, knownHostsFile: string): string[] {
	const lines = [
		`Host ${host.alias}`,
		"    HostName 127.0.0.1",
		`    Port ${host.port}`,
	];

	// The username names the job or session to reach; it carries no
	// identity, because the relay already established that. An empty target
	// means the caller's default session, and ssh sends the local
	// username when none is given -- which would name a session after
	// whatever the laptop calls its owner. `default` says it outright.
	lines.push(`    User ${host.target.trim() === "" ? "default" : host.target.trim()}`);

	// HostKeyAlias is what makes host verification work through the
	// loopback hop, and leaving it out fails in a way that looks like
	// nothing to do with it.
	//
	// Without it ssh verifies the name it dialled: `127.0.0.1`. The
	// gateway's certificate is issued for the access point's public
	// name, and the published @cert-authority line is scoped to that
	// name too, so both checks miss and the user is asked to trust an
	// unknown host -- the exact prompt this whole design exists to
	// remove. With it, both the known_hosts lookup and the
	// certificate's principal check use the real name.
	if (host.gatewayName) {
		lines.push(`    HostKeyAlias ${host.gatewayName}`);
	}

	lines.push(
		`    UserKnownHostsFile ${quote(knownHostsFile)}`,
		"    StrictHostKeyChecking yes",
		// No credential is offered and none is wanted: the relay
		// authenticated this connection before ssh started. Offering
		// agent keys would spend authentication attempts announcing
		// keys the gateway has no interest in.
		"    PubkeyAuthentication no",
		"    PasswordAuthentication no",
		"    KbdInteractiveAuthentication no",
		"    IdentitiesOnly yes",
		// Remote-SSH opens several channels over one connection; a
		// dropped keepalive mid-edit shows up as the editor
		// disconnecting for no visible reason.
		"    ServerAliveInterval 30",
		"    ServerAliveCountMax 6"
	);
	return lines;
}

/**
 * Quote a path for ssh_config.
 *
 * Needed on Windows before anywhere else: the extension's storage
 * directory sits under a user profile, and a user called "Jo Smith"
 * produces a path with a space in it that ssh otherwise reads as two
 * arguments.
 */
function quote(path: string): string {
	return `"${path.replace(/"/g, '\\"')}"`;
}
